// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPACustomerVersionProfile
    {
        public static Task<GetZPACustomerVersionProfileResult> InvokeAsync(GetZPACustomerVersionProfileArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPACustomerVersionProfileResult>("zpa:index/getZPACustomerVersionProfile:getZPACustomerVersionProfile", args ?? new GetZPACustomerVersionProfileArgs(), options.WithDefaults());

        public static Output<GetZPACustomerVersionProfileResult> Invoke(GetZPACustomerVersionProfileInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPACustomerVersionProfileResult>("zpa:index/getZPACustomerVersionProfile:getZPACustomerVersionProfile", args ?? new GetZPACustomerVersionProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPACustomerVersionProfileArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetZPACustomerVersionProfileArgs()
        {
        }
    }

    public sealed class GetZPACustomerVersionProfileInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetZPACustomerVersionProfileInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPACustomerVersionProfileResult
    {
        public readonly string CreationTime;
        public readonly ImmutableArray<Outputs.GetZPACustomerVersionProfileCustomScopeCustomerIdResult> CustomScopeCustomerIds;
        public readonly string CustomerId;
        public readonly string Description;
        public readonly string Id;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string Name;
        public readonly string UpgradePriority;
        public readonly ImmutableArray<Outputs.GetZPACustomerVersionProfileVersionResult> Versions;
        public readonly string VisibilityScope;

        [OutputConstructor]
        private GetZPACustomerVersionProfileResult(
            string creationTime,

            ImmutableArray<Outputs.GetZPACustomerVersionProfileCustomScopeCustomerIdResult> customScopeCustomerIds,

            string customerId,

            string description,

            string id,

            string modifiedTime,

            string modifiedby,

            string name,

            string upgradePriority,

            ImmutableArray<Outputs.GetZPACustomerVersionProfileVersionResult> versions,

            string visibilityScope)
        {
            CreationTime = creationTime;
            CustomScopeCustomerIds = customScopeCustomerIds;
            CustomerId = customerId;
            Description = description;
            Id = id;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            UpgradePriority = upgradePriority;
            Versions = versions;
            VisibilityScope = visibilityScope;
        }
    }
}
