// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPALSSConfigMachineGroup
    {
        public static Task<GetZPALSSConfigMachineGroupResult> InvokeAsync(GetZPALSSConfigMachineGroupArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPALSSConfigMachineGroupResult>("zpa:index/getZPALSSConfigMachineGroup:getZPALSSConfigMachineGroup", args ?? new GetZPALSSConfigMachineGroupArgs(), options.WithDefaults());

        public static Output<GetZPALSSConfigMachineGroupResult> Invoke(GetZPALSSConfigMachineGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPALSSConfigMachineGroupResult>("zpa:index/getZPALSSConfigMachineGroup:getZPALSSConfigMachineGroup", args ?? new GetZPALSSConfigMachineGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPALSSConfigMachineGroupArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetZPALSSConfigMachineGroupArgs()
        {
        }
    }

    public sealed class GetZPALSSConfigMachineGroupInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetZPALSSConfigMachineGroupInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPALSSConfigMachineGroupResult
    {
        public readonly string CreationTime;
        public readonly string Description;
        public readonly bool Enabled;
        public readonly string? Id;
        public readonly ImmutableArray<Outputs.GetZPALSSConfigMachineGroupMachineResult> Machines;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string? Name;

        [OutputConstructor]
        private GetZPALSSConfigMachineGroupResult(
            string creationTime,

            string description,

            bool enabled,

            string? id,

            ImmutableArray<Outputs.GetZPALSSConfigMachineGroupMachineResult> machines,

            string modifiedTime,

            string modifiedby,

            string? name)
        {
            CreationTime = creationTime;
            Description = description;
            Enabled = enabled;
            Id = id;
            Machines = machines;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
        }
    }
}
