// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPAAppSegmentBrowserAccess
    {
        public static Task<GetZPAAppSegmentBrowserAccessResult> InvokeAsync(GetZPAAppSegmentBrowserAccessArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPAAppSegmentBrowserAccessResult>("zpa:index/getZPAAppSegmentBrowserAccess:getZPAAppSegmentBrowserAccess", args ?? new GetZPAAppSegmentBrowserAccessArgs(), options.WithDefaults());

        public static Output<GetZPAAppSegmentBrowserAccessResult> Invoke(GetZPAAppSegmentBrowserAccessInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPAAppSegmentBrowserAccessResult>("zpa:index/getZPAAppSegmentBrowserAccess:getZPAAppSegmentBrowserAccess", args ?? new GetZPAAppSegmentBrowserAccessInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPAAppSegmentBrowserAccessArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("tcpPortRanges")]
        private List<Inputs.GetZPAAppSegmentBrowserAccessTcpPortRangeArgs>? _tcpPortRanges;
        public List<Inputs.GetZPAAppSegmentBrowserAccessTcpPortRangeArgs> TcpPortRanges
        {
            get => _tcpPortRanges ?? (_tcpPortRanges = new List<Inputs.GetZPAAppSegmentBrowserAccessTcpPortRangeArgs>());
            set => _tcpPortRanges = value;
        }

        [Input("udpPortRanges")]
        private List<Inputs.GetZPAAppSegmentBrowserAccessUdpPortRangeArgs>? _udpPortRanges;
        public List<Inputs.GetZPAAppSegmentBrowserAccessUdpPortRangeArgs> UdpPortRanges
        {
            get => _udpPortRanges ?? (_udpPortRanges = new List<Inputs.GetZPAAppSegmentBrowserAccessUdpPortRangeArgs>());
            set => _udpPortRanges = value;
        }

        public GetZPAAppSegmentBrowserAccessArgs()
        {
        }
    }

    public sealed class GetZPAAppSegmentBrowserAccessInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tcpPortRanges")]
        private InputList<Inputs.GetZPAAppSegmentBrowserAccessTcpPortRangeInputArgs>? _tcpPortRanges;
        public InputList<Inputs.GetZPAAppSegmentBrowserAccessTcpPortRangeInputArgs> TcpPortRanges
        {
            get => _tcpPortRanges ?? (_tcpPortRanges = new InputList<Inputs.GetZPAAppSegmentBrowserAccessTcpPortRangeInputArgs>());
            set => _tcpPortRanges = value;
        }

        [Input("udpPortRanges")]
        private InputList<Inputs.GetZPAAppSegmentBrowserAccessUdpPortRangeInputArgs>? _udpPortRanges;
        public InputList<Inputs.GetZPAAppSegmentBrowserAccessUdpPortRangeInputArgs> UdpPortRanges
        {
            get => _udpPortRanges ?? (_udpPortRanges = new InputList<Inputs.GetZPAAppSegmentBrowserAccessUdpPortRangeInputArgs>());
            set => _udpPortRanges = value;
        }

        public GetZPAAppSegmentBrowserAccessInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPAAppSegmentBrowserAccessResult
    {
        public readonly string BypassType;
        public readonly ImmutableArray<Outputs.GetZPAAppSegmentBrowserAccessClientlessAppResult> ClientlessApps;
        public readonly string ConfigSpace;
        public readonly string Description;
        public readonly ImmutableArray<string> DomainNames;
        public readonly bool DoubleEncrypt;
        public readonly bool Enabled;
        public readonly string HealthCheckType;
        public readonly string HealthReporting;
        public readonly string? Id;
        public readonly bool IpAnchored;
        public readonly bool IsCnameEnabled;
        public readonly string? Name;
        public readonly bool PassiveHealthEnabled;
        public readonly string SegmentGroupId;
        public readonly string SegmentGroupName;
        public readonly ImmutableArray<Outputs.GetZPAAppSegmentBrowserAccessServerGroupResult> ServerGroups;
        public readonly ImmutableArray<string> TcpPortRanges;
        public readonly ImmutableArray<string> UdpPortRanges;

        [OutputConstructor]
        private GetZPAAppSegmentBrowserAccessResult(
            string bypassType,

            ImmutableArray<Outputs.GetZPAAppSegmentBrowserAccessClientlessAppResult> clientlessApps,

            string configSpace,

            string description,

            ImmutableArray<string> domainNames,

            bool doubleEncrypt,

            bool enabled,

            string healthCheckType,

            string healthReporting,

            string? id,

            bool ipAnchored,

            bool isCnameEnabled,

            string? name,

            bool passiveHealthEnabled,

            string segmentGroupId,

            string segmentGroupName,

            ImmutableArray<Outputs.GetZPAAppSegmentBrowserAccessServerGroupResult> serverGroups,

            ImmutableArray<string> tcpPortRanges,

            ImmutableArray<string> udpPortRanges)
        {
            BypassType = bypassType;
            ClientlessApps = clientlessApps;
            ConfigSpace = configSpace;
            Description = description;
            DomainNames = domainNames;
            DoubleEncrypt = doubleEncrypt;
            Enabled = enabled;
            HealthCheckType = healthCheckType;
            HealthReporting = healthReporting;
            Id = id;
            IpAnchored = ipAnchored;
            IsCnameEnabled = isCnameEnabled;
            Name = name;
            PassiveHealthEnabled = passiveHealthEnabled;
            SegmentGroupId = segmentGroupId;
            SegmentGroupName = segmentGroupName;
            ServerGroups = serverGroups;
            TcpPortRanges = tcpPortRanges;
            UdpPortRanges = udpPortRanges;
        }
    }
}
