// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPASegmentGroup
    {
        public static Task<GetZPASegmentGroupResult> InvokeAsync(GetZPASegmentGroupArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPASegmentGroupResult>("zpa:index/getZPASegmentGroup:getZPASegmentGroup", args ?? new GetZPASegmentGroupArgs(), options.WithDefaults());

        public static Output<GetZPASegmentGroupResult> Invoke(GetZPASegmentGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPASegmentGroupResult>("zpa:index/getZPASegmentGroup:getZPASegmentGroup", args ?? new GetZPASegmentGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPASegmentGroupArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("policyMigrated")]
        public bool? PolicyMigrated { get; set; }

        public GetZPASegmentGroupArgs()
        {
        }
    }

    public sealed class GetZPASegmentGroupInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("policyMigrated")]
        public Input<bool>? PolicyMigrated { get; set; }

        public GetZPASegmentGroupInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPASegmentGroupResult
    {
        public readonly ImmutableArray<Outputs.GetZPASegmentGroupApplicationResult> Applications;
        public readonly string ConfigSpace;
        public readonly string CreationTime;
        public readonly string Description;
        public readonly bool Enabled;
        public readonly string? Id;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string? Name;
        public readonly bool PolicyMigrated;
        public readonly string TcpKeepAliveEnabled;

        [OutputConstructor]
        private GetZPASegmentGroupResult(
            ImmutableArray<Outputs.GetZPASegmentGroupApplicationResult> applications,

            string configSpace,

            string creationTime,

            string description,

            bool enabled,

            string? id,

            string modifiedTime,

            string modifiedby,

            string? name,

            bool policyMigrated,

            string tcpKeepAliveEnabled)
        {
            Applications = applications;
            ConfigSpace = configSpace;
            CreationTime = creationTime;
            Description = description;
            Enabled = enabled;
            Id = id;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            PolicyMigrated = policyMigrated;
            TcpKeepAliveEnabled = tcpKeepAliveEnabled;
        }
    }
}
