// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPAPostureProfile
    {
        public static Task<GetZPAPostureProfileResult> InvokeAsync(GetZPAPostureProfileArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPAPostureProfileResult>("zpa:index/getZPAPostureProfile:getZPAPostureProfile", args ?? new GetZPAPostureProfileArgs(), options.WithDefaults());

        public static Output<GetZPAPostureProfileResult> Invoke(GetZPAPostureProfileInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPAPostureProfileResult>("zpa:index/getZPAPostureProfile:getZPAPostureProfile", args ?? new GetZPAPostureProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPAPostureProfileArgs : Pulumi.InvokeArgs
    {
        [Input("name")]
        public string? Name { get; set; }

        public GetZPAPostureProfileArgs()
        {
        }
    }

    public sealed class GetZPAPostureProfileInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetZPAPostureProfileInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPAPostureProfileResult
    {
        public readonly string CreationTime;
        public readonly string Domain;
        public readonly string Id;
        public readonly string MasterCustomerId;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string? Name;
        public readonly string PostureUdid;
        public readonly string ZscalerCloud;
        public readonly string ZscalerCustomerId;

        [OutputConstructor]
        private GetZPAPostureProfileResult(
            string creationTime,

            string domain,

            string id,

            string masterCustomerId,

            string modifiedTime,

            string modifiedby,

            string? name,

            string postureUdid,

            string zscalerCloud,

            string zscalerCustomerId)
        {
            CreationTime = creationTime;
            Domain = domain;
            Id = id;
            MasterCustomerId = masterCustomerId;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            PostureUdid = postureUdid;
            ZscalerCloud = zscalerCloud;
            ZscalerCustomerId = zscalerCustomerId;
        }
    }
}
