// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPALSSConfigStatusCodes
    {
        public static Task<GetZPALSSConfigStatusCodesResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPALSSConfigStatusCodesResult>("zpa:index/getZPALSSConfigStatusCodes:getZPALSSConfigStatusCodes", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetZPALSSConfigStatusCodesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> ZpnAstAuthLog;
        public readonly ImmutableDictionary<string, string> ZpnAuthLog;
        public readonly ImmutableDictionary<string, string> ZpnSysAuthLog;
        public readonly ImmutableDictionary<string, string> ZpnTransLog;

        [OutputConstructor]
        private GetZPALSSConfigStatusCodesResult(
            string id,

            ImmutableDictionary<string, string> zpnAstAuthLog,

            ImmutableDictionary<string, string> zpnAuthLog,

            ImmutableDictionary<string, string> zpnSysAuthLog,

            ImmutableDictionary<string, string> zpnTransLog)
        {
            Id = id;
            ZpnAstAuthLog = zpnAstAuthLog;
            ZpnAuthLog = zpnAuthLog;
            ZpnSysAuthLog = zpnSysAuthLog;
            ZpnTransLog = zpnTransLog;
        }
    }
}
