// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPASCIMGroups
    {
        public static Task<GetZPASCIMGroupsResult> InvokeAsync(GetZPASCIMGroupsArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPASCIMGroupsResult>("zpa:index/getZPASCIMGroups:getZPASCIMGroups", args ?? new GetZPASCIMGroupsArgs(), options.WithDefaults());

        public static Output<GetZPASCIMGroupsResult> Invoke(GetZPASCIMGroupsInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPASCIMGroupsResult>("zpa:index/getZPASCIMGroups:getZPASCIMGroups", args ?? new GetZPASCIMGroupsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPASCIMGroupsArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("idpId")]
        public int? IdpId { get; set; }

        [Input("idpName")]
        public string? IdpName { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetZPASCIMGroupsArgs()
        {
        }
    }

    public sealed class GetZPASCIMGroupsInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("idpId")]
        public Input<int>? IdpId { get; set; }

        [Input("idpName")]
        public Input<string>? IdpName { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetZPASCIMGroupsInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPASCIMGroupsResult
    {
        public readonly int CreationTime;
        public readonly string? Id;
        public readonly string IdpGroupId;
        public readonly int? IdpId;
        public readonly string? IdpName;
        public readonly int ModifiedTime;
        public readonly string? Name;

        [OutputConstructor]
        private GetZPASCIMGroupsResult(
            int creationTime,

            string? id,

            string idpGroupId,

            int? idpId,

            string? idpName,

            int modifiedTime,

            string? name)
        {
            CreationTime = creationTime;
            Id = id;
            IdpGroupId = idpGroupId;
            IdpId = idpId;
            IdpName = idpName;
            ModifiedTime = modifiedTime;
            Name = name;
        }
    }
}
