// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPALSSConfigLogTypeFormats
    {
        public static Task<GetZPALSSConfigLogTypeFormatsResult> InvokeAsync(GetZPALSSConfigLogTypeFormatsArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPALSSConfigLogTypeFormatsResult>("zpa:index/getZPALSSConfigLogTypeFormats:getZPALSSConfigLogTypeFormats", args ?? new GetZPALSSConfigLogTypeFormatsArgs(), options.WithDefaults());

        public static Output<GetZPALSSConfigLogTypeFormatsResult> Invoke(GetZPALSSConfigLogTypeFormatsInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPALSSConfigLogTypeFormatsResult>("zpa:index/getZPALSSConfigLogTypeFormats:getZPALSSConfigLogTypeFormats", args ?? new GetZPALSSConfigLogTypeFormatsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPALSSConfigLogTypeFormatsArgs : Pulumi.InvokeArgs
    {
        [Input("logType", required: true)]
        public string LogType { get; set; } = null!;

        public GetZPALSSConfigLogTypeFormatsArgs()
        {
        }
    }

    public sealed class GetZPALSSConfigLogTypeFormatsInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("logType", required: true)]
        public Input<string> LogType { get; set; } = null!;

        public GetZPALSSConfigLogTypeFormatsInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPALSSConfigLogTypeFormatsResult
    {
        public readonly string Csv;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Json;
        public readonly string LogType;
        public readonly string Tsv;

        [OutputConstructor]
        private GetZPALSSConfigLogTypeFormatsResult(
            string csv,

            string id,

            string json,

            string logType,

            string tsv)
        {
            Csv = csv;
            Id = id;
            Json = json;
            LogType = logType;
            Tsv = tsv;
        }
    }
}
