// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    public static class GetZPAAppConnectorController
    {
        public static Task<GetZPAAppConnectorControllerResult> InvokeAsync(GetZPAAppConnectorControllerArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZPAAppConnectorControllerResult>("zpa:index/getZPAAppConnectorController:getZPAAppConnectorController", args ?? new GetZPAAppConnectorControllerArgs(), options.WithDefaults());

        public static Output<GetZPAAppConnectorControllerResult> Invoke(GetZPAAppConnectorControllerInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetZPAAppConnectorControllerResult>("zpa:index/getZPAAppConnectorController:getZPAAppConnectorController", args ?? new GetZPAAppConnectorControllerInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZPAAppConnectorControllerArgs : Pulumi.InvokeArgs
    {
        [Input("name")]
        public string? Name { get; set; }

        public GetZPAAppConnectorControllerArgs()
        {
        }
    }

    public sealed class GetZPAAppConnectorControllerInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetZPAAppConnectorControllerInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetZPAAppConnectorControllerResult
    {
        public readonly string AppConnectorGroupId;
        public readonly string AppConnectorGroupName;
        public readonly string ApplicationStartTime;
        public readonly string ControlChannelStatus;
        public readonly string CreationTime;
        public readonly string CtrlBrokerName;
        public readonly string CurrentVersion;
        public readonly string Description;
        public readonly bool Enabled;
        public readonly ImmutableDictionary<string, object> EnrollmentCert;
        public readonly string ExpectedUpgradeTime;
        public readonly string ExpectedVersion;
        public readonly string Fingerprint;
        public readonly string Id;
        public readonly string IpAcl;
        public readonly string IssuedCertId;
        public readonly string LastBrokerConnectTime;
        public readonly string LastBrokerConnectTimeDuration;
        public readonly string LastBrokerDisconnectTime;
        public readonly string LastBrokerDisconnectTimeDuration;
        public readonly string LastUpgradeTime;
        public readonly string Latitude;
        public readonly string Location;
        public readonly string Longitude;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string? Name;
        public readonly string Platform;
        public readonly string PreviousVersion;
        public readonly string PrivateIp;
        public readonly string ProvisioningKeyId;
        public readonly string ProvisioningKeyName;
        public readonly string PublicIp;
        public readonly string SargeVersion;
        public readonly string UpgradeAttempt;
        public readonly string UpgradeStatus;

        [OutputConstructor]
        private GetZPAAppConnectorControllerResult(
            string appConnectorGroupId,

            string appConnectorGroupName,

            string applicationStartTime,

            string controlChannelStatus,

            string creationTime,

            string ctrlBrokerName,

            string currentVersion,

            string description,

            bool enabled,

            ImmutableDictionary<string, object> enrollmentCert,

            string expectedUpgradeTime,

            string expectedVersion,

            string fingerprint,

            string id,

            string ipAcl,

            string issuedCertId,

            string lastBrokerConnectTime,

            string lastBrokerConnectTimeDuration,

            string lastBrokerDisconnectTime,

            string lastBrokerDisconnectTimeDuration,

            string lastUpgradeTime,

            string latitude,

            string location,

            string longitude,

            string modifiedTime,

            string modifiedby,

            string? name,

            string platform,

            string previousVersion,

            string privateIp,

            string provisioningKeyId,

            string provisioningKeyName,

            string publicIp,

            string sargeVersion,

            string upgradeAttempt,

            string upgradeStatus)
        {
            AppConnectorGroupId = appConnectorGroupId;
            AppConnectorGroupName = appConnectorGroupName;
            ApplicationStartTime = applicationStartTime;
            ControlChannelStatus = controlChannelStatus;
            CreationTime = creationTime;
            CtrlBrokerName = ctrlBrokerName;
            CurrentVersion = currentVersion;
            Description = description;
            Enabled = enabled;
            EnrollmentCert = enrollmentCert;
            ExpectedUpgradeTime = expectedUpgradeTime;
            ExpectedVersion = expectedVersion;
            Fingerprint = fingerprint;
            Id = id;
            IpAcl = ipAcl;
            IssuedCertId = issuedCertId;
            LastBrokerConnectTime = lastBrokerConnectTime;
            LastBrokerConnectTimeDuration = lastBrokerConnectTimeDuration;
            LastBrokerDisconnectTime = lastBrokerDisconnectTime;
            LastBrokerDisconnectTimeDuration = lastBrokerDisconnectTimeDuration;
            LastUpgradeTime = lastUpgradeTime;
            Latitude = latitude;
            Location = location;
            Longitude = longitude;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            Platform = platform;
            PreviousVersion = previousVersion;
            PrivateIp = privateIp;
            ProvisioningKeyId = provisioningKeyId;
            ProvisioningKeyName = provisioningKeyName;
            PublicIp = publicIp;
            SargeVersion = sargeVersion;
            UpgradeAttempt = upgradeAttempt;
            UpgradeStatus = upgradeStatus;
        }
    }
}
