// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr
{
    [willguibrResourceType("zpa:index/zPAProvisioningKey:ZPAProvisioningKey")]
    public partial class ZPAProvisioningKey : Pulumi.CustomResource
    {
        [Output("appConnectorGroupId")]
        public Output<string?> AppConnectorGroupId { get; private set; } = null!;

        /// <summary>
        /// Read only property. Applicable only for GET calls, ignored in PUT/POST calls.
        /// </summary>
        [Output("appConnectorGroupName")]
        public Output<string> AppConnectorGroupName { get; private set; } = null!;

        /// <summary>
        /// Specifies the provisioning key type for App Connectors or ZPA Private Service Edges. The supported values are
        /// CONNECTOR_GRP and SERVICE_EDGE_GRP.
        /// </summary>
        [Output("associationType")]
        public Output<string> AssociationType { get; private set; } = null!;

        /// <summary>
        /// Whether the provisioning key is enabled or not. Supported values: true, false
        /// </summary>
        [Output("enabled")]
        public Output<bool?> Enabled { get; private set; } = null!;

        /// <summary>
        /// ID of the enrollment certificate that can be used for this provisioning key.
        /// </summary>
        [Output("enrollmentCertId")]
        public Output<string> EnrollmentCertId { get; private set; } = null!;

        /// <summary>
        /// Read only property. Applicable only for GET calls, ignored in PUT/POST calls.
        /// </summary>
        [Output("enrollmentCertName")]
        public Output<string> EnrollmentCertName { get; private set; } = null!;

        [Output("ipAcls")]
        public Output<ImmutableArray<string>> IpAcls { get; private set; } = null!;

        /// <summary>
        /// The maximum number of instances where this provisioning key can be used for enrolling an App Connector or Service Edge.
        /// </summary>
        [Output("maxUsage")]
        public Output<string> MaxUsage { get; private set; } = null!;

        /// <summary>
        /// Name of the provisioning key.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// read only field. Ignored in PUT/POST calls.
        /// </summary>
        [Output("provisioningKey")]
        public Output<string> ProvisioningKey { get; private set; } = null!;

        [Output("uiConfig")]
        public Output<string?> UiConfig { get; private set; } = null!;

        /// <summary>
        /// The provisioning key utilization count.
        /// </summary>
        [Output("usageCount")]
        public Output<string> UsageCount { get; private set; } = null!;

        /// <summary>
        /// ID of the existing App Connector or Service Edge Group.
        /// </summary>
        [Output("zcomponentId")]
        public Output<string> ZcomponentId { get; private set; } = null!;

        /// <summary>
        /// Read only property. Applicable only for GET calls, ignored in PUT/POST calls.
        /// </summary>
        [Output("zcomponentName")]
        public Output<string> ZcomponentName { get; private set; } = null!;


        /// <summary>
        /// Create a ZPAProvisioningKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ZPAProvisioningKey(string name, ZPAProvisioningKeyArgs args, CustomResourceOptions? options = null)
            : base("zpa:index/zPAProvisioningKey:ZPAProvisioningKey", name, args ?? new ZPAProvisioningKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ZPAProvisioningKey(string name, Input<string> id, ZPAProvisioningKeyState? state = null, CustomResourceOptions? options = null)
            : base("zpa:index/zPAProvisioningKey:ZPAProvisioningKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/willguibr/pulumi-zpa/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ZPAProvisioningKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ZPAProvisioningKey Get(string name, Input<string> id, ZPAProvisioningKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new ZPAProvisioningKey(name, id, state, options);
        }
    }

    public sealed class ZPAProvisioningKeyArgs : Pulumi.ResourceArgs
    {
        [Input("appConnectorGroupId")]
        public Input<string>? AppConnectorGroupId { get; set; }

        /// <summary>
        /// Specifies the provisioning key type for App Connectors or ZPA Private Service Edges. The supported values are
        /// CONNECTOR_GRP and SERVICE_EDGE_GRP.
        /// </summary>
        [Input("associationType", required: true)]
        public Input<string> AssociationType { get; set; } = null!;

        /// <summary>
        /// Whether the provisioning key is enabled or not. Supported values: true, false
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// ID of the enrollment certificate that can be used for this provisioning key.
        /// </summary>
        [Input("enrollmentCertId", required: true)]
        public Input<string> EnrollmentCertId { get; set; } = null!;

        [Input("ipAcls")]
        private InputList<string>? _ipAcls;
        public InputList<string> IpAcls
        {
            get => _ipAcls ?? (_ipAcls = new InputList<string>());
            set => _ipAcls = value;
        }

        /// <summary>
        /// The maximum number of instances where this provisioning key can be used for enrolling an App Connector or Service Edge.
        /// </summary>
        [Input("maxUsage", required: true)]
        public Input<string> MaxUsage { get; set; } = null!;

        /// <summary>
        /// Name of the provisioning key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("uiConfig")]
        public Input<string>? UiConfig { get; set; }

        /// <summary>
        /// The provisioning key utilization count.
        /// </summary>
        [Input("usageCount")]
        public Input<string>? UsageCount { get; set; }

        /// <summary>
        /// ID of the existing App Connector or Service Edge Group.
        /// </summary>
        [Input("zcomponentId", required: true)]
        public Input<string> ZcomponentId { get; set; } = null!;

        /// <summary>
        /// Read only property. Applicable only for GET calls, ignored in PUT/POST calls.
        /// </summary>
        [Input("zcomponentName")]
        public Input<string>? ZcomponentName { get; set; }

        public ZPAProvisioningKeyArgs()
        {
        }
    }

    public sealed class ZPAProvisioningKeyState : Pulumi.ResourceArgs
    {
        [Input("appConnectorGroupId")]
        public Input<string>? AppConnectorGroupId { get; set; }

        /// <summary>
        /// Read only property. Applicable only for GET calls, ignored in PUT/POST calls.
        /// </summary>
        [Input("appConnectorGroupName")]
        public Input<string>? AppConnectorGroupName { get; set; }

        /// <summary>
        /// Specifies the provisioning key type for App Connectors or ZPA Private Service Edges. The supported values are
        /// CONNECTOR_GRP and SERVICE_EDGE_GRP.
        /// </summary>
        [Input("associationType")]
        public Input<string>? AssociationType { get; set; }

        /// <summary>
        /// Whether the provisioning key is enabled or not. Supported values: true, false
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// ID of the enrollment certificate that can be used for this provisioning key.
        /// </summary>
        [Input("enrollmentCertId")]
        public Input<string>? EnrollmentCertId { get; set; }

        /// <summary>
        /// Read only property. Applicable only for GET calls, ignored in PUT/POST calls.
        /// </summary>
        [Input("enrollmentCertName")]
        public Input<string>? EnrollmentCertName { get; set; }

        [Input("ipAcls")]
        private InputList<string>? _ipAcls;
        public InputList<string> IpAcls
        {
            get => _ipAcls ?? (_ipAcls = new InputList<string>());
            set => _ipAcls = value;
        }

        /// <summary>
        /// The maximum number of instances where this provisioning key can be used for enrolling an App Connector or Service Edge.
        /// </summary>
        [Input("maxUsage")]
        public Input<string>? MaxUsage { get; set; }

        /// <summary>
        /// Name of the provisioning key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// read only field. Ignored in PUT/POST calls.
        /// </summary>
        [Input("provisioningKey")]
        public Input<string>? ProvisioningKey { get; set; }

        [Input("uiConfig")]
        public Input<string>? UiConfig { get; set; }

        /// <summary>
        /// The provisioning key utilization count.
        /// </summary>
        [Input("usageCount")]
        public Input<string>? UsageCount { get; set; }

        /// <summary>
        /// ID of the existing App Connector or Service Edge Group.
        /// </summary>
        [Input("zcomponentId")]
        public Input<string>? ZcomponentId { get; set; }

        /// <summary>
        /// Read only property. Applicable only for GET calls, ignored in PUT/POST calls.
        /// </summary>
        [Input("zcomponentName")]
        public Input<string>? ZcomponentName { get; set; }

        public ZPAProvisioningKeyState()
        {
        }
    }
}
