// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetZPAServiceEdgeController(ctx *pulumi.Context, args *GetZPAServiceEdgeControllerArgs, opts ...pulumi.InvokeOption) (*GetZPAServiceEdgeControllerResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetZPAServiceEdgeControllerResult
	err := ctx.Invoke("zpa:index/getZPAServiceEdgeController:getZPAServiceEdgeController", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPAServiceEdgeController.
type GetZPAServiceEdgeControllerArgs struct {
	Name *string `pulumi:"name"`
}

// A collection of values returned by getZPAServiceEdgeController.
type GetZPAServiceEdgeControllerResult struct {
	ApplicationStartTime             string                 `pulumi:"applicationStartTime"`
	ControlChannelStatus             string                 `pulumi:"controlChannelStatus"`
	CreationTime                     string                 `pulumi:"creationTime"`
	CtrlBrokerName                   string                 `pulumi:"ctrlBrokerName"`
	CurrentVersion                   string                 `pulumi:"currentVersion"`
	Description                      string                 `pulumi:"description"`
	Enabled                          bool                   `pulumi:"enabled"`
	EnrollmentCert                   map[string]interface{} `pulumi:"enrollmentCert"`
	ExpectedUpgradeTime              string                 `pulumi:"expectedUpgradeTime"`
	ExpectedVersion                  string                 `pulumi:"expectedVersion"`
	Fingerprint                      string                 `pulumi:"fingerprint"`
	Id                               string                 `pulumi:"id"`
	IpAcl                            string                 `pulumi:"ipAcl"`
	IssuedCertId                     string                 `pulumi:"issuedCertId"`
	LastBrokerConnectTime            string                 `pulumi:"lastBrokerConnectTime"`
	LastBrokerConnectTimeDuration    string                 `pulumi:"lastBrokerConnectTimeDuration"`
	LastBrokerDisconnectTime         string                 `pulumi:"lastBrokerDisconnectTime"`
	LastBrokerDisconnectTimeDuration string                 `pulumi:"lastBrokerDisconnectTimeDuration"`
	LastUpgradeTime                  string                 `pulumi:"lastUpgradeTime"`
	Latitude                         string                 `pulumi:"latitude"`
	ListenIps                        string                 `pulumi:"listenIps"`
	Location                         string                 `pulumi:"location"`
	Longitude                        string                 `pulumi:"longitude"`
	ModifiedTime                     string                 `pulumi:"modifiedTime"`
	Modifiedby                       string                 `pulumi:"modifiedby"`
	Name                             *string                `pulumi:"name"`
	Platform                         string                 `pulumi:"platform"`
	PreviousVersion                  string                 `pulumi:"previousVersion"`
	PrivateIp                        string                 `pulumi:"privateIp"`
	ProvisioningKeyId                string                 `pulumi:"provisioningKeyId"`
	ProvisioningKeyName              string                 `pulumi:"provisioningKeyName"`
	PublicIp                         string                 `pulumi:"publicIp"`
	PublishIps                       string                 `pulumi:"publishIps"`
	SargeVersion                     string                 `pulumi:"sargeVersion"`
	ServiceEdgeGroupId               string                 `pulumi:"serviceEdgeGroupId"`
	ServiceEdgeGroupName             string                 `pulumi:"serviceEdgeGroupName"`
	UpgradeAttempt                   string                 `pulumi:"upgradeAttempt"`
	UpgradeStatus                    string                 `pulumi:"upgradeStatus"`
}

func GetZPAServiceEdgeControllerOutput(ctx *pulumi.Context, args GetZPAServiceEdgeControllerOutputArgs, opts ...pulumi.InvokeOption) GetZPAServiceEdgeControllerResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetZPAServiceEdgeControllerResult, error) {
			args := v.(GetZPAServiceEdgeControllerArgs)
			r, err := GetZPAServiceEdgeController(ctx, &args, opts...)
			var s GetZPAServiceEdgeControllerResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetZPAServiceEdgeControllerResultOutput)
}

// A collection of arguments for invoking getZPAServiceEdgeController.
type GetZPAServiceEdgeControllerOutputArgs struct {
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetZPAServiceEdgeControllerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPAServiceEdgeControllerArgs)(nil)).Elem()
}

// A collection of values returned by getZPAServiceEdgeController.
type GetZPAServiceEdgeControllerResultOutput struct{ *pulumi.OutputState }

func (GetZPAServiceEdgeControllerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPAServiceEdgeControllerResult)(nil)).Elem()
}

func (o GetZPAServiceEdgeControllerResultOutput) ToGetZPAServiceEdgeControllerResultOutput() GetZPAServiceEdgeControllerResultOutput {
	return o
}

func (o GetZPAServiceEdgeControllerResultOutput) ToGetZPAServiceEdgeControllerResultOutputWithContext(ctx context.Context) GetZPAServiceEdgeControllerResultOutput {
	return o
}

func (o GetZPAServiceEdgeControllerResultOutput) ApplicationStartTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ApplicationStartTime }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ControlChannelStatus() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ControlChannelStatus }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) CtrlBrokerName() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.CtrlBrokerName }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) CurrentVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.CurrentVersion }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) EnrollmentCert() pulumi.MapOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) map[string]interface{} { return v.EnrollmentCert }).(pulumi.MapOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ExpectedUpgradeTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ExpectedUpgradeTime }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ExpectedVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ExpectedVersion }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Fingerprint }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) IpAcl() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.IpAcl }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) IssuedCertId() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.IssuedCertId }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) LastBrokerConnectTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.LastBrokerConnectTime }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) LastBrokerConnectTimeDuration() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.LastBrokerConnectTimeDuration }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) LastBrokerDisconnectTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.LastBrokerDisconnectTime }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) LastBrokerDisconnectTimeDuration() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.LastBrokerDisconnectTimeDuration }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) LastUpgradeTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.LastUpgradeTime }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Latitude() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Latitude }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ListenIps() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ListenIps }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Longitude() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Longitude }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) Platform() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.Platform }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) PreviousVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.PreviousVersion }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.PrivateIp }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ProvisioningKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ProvisioningKeyId }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ProvisioningKeyName() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ProvisioningKeyName }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.PublicIp }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) PublishIps() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.PublishIps }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) SargeVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.SargeVersion }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ServiceEdgeGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ServiceEdgeGroupId }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) ServiceEdgeGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.ServiceEdgeGroupName }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) UpgradeAttempt() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.UpgradeAttempt }).(pulumi.StringOutput)
}

func (o GetZPAServiceEdgeControllerResultOutput) UpgradeStatus() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPAServiceEdgeControllerResult) string { return v.UpgradeStatus }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetZPAServiceEdgeControllerResultOutput{})
}
