// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetZPASCIMAttributeHeader(ctx *pulumi.Context, args *GetZPASCIMAttributeHeaderArgs, opts ...pulumi.InvokeOption) (*GetZPASCIMAttributeHeaderResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetZPASCIMAttributeHeaderResult
	err := ctx.Invoke("zpa:index/getZPASCIMAttributeHeader:getZPASCIMAttributeHeader", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderArgs struct {
	IdpName *string `pulumi:"idpName"`
	Name    *string `pulumi:"name"`
}

// A collection of values returned by getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderResult struct {
	CanonicalValues []string `pulumi:"canonicalValues"`
	CaseSensitive   bool     `pulumi:"caseSensitive"`
	CreationTime    string   `pulumi:"creationTime"`
	DataType        string   `pulumi:"dataType"`
	Description     string   `pulumi:"description"`
	Id              string   `pulumi:"id"`
	IdpId           string   `pulumi:"idpId"`
	IdpName         *string  `pulumi:"idpName"`
	ModifiedTime    string   `pulumi:"modifiedTime"`
	Modifiedby      string   `pulumi:"modifiedby"`
	Multivalued     bool     `pulumi:"multivalued"`
	Mutability      string   `pulumi:"mutability"`
	Name            *string  `pulumi:"name"`
	Required        bool     `pulumi:"required"`
	Returned        string   `pulumi:"returned"`
	SchemaUri       string   `pulumi:"schemaUri"`
	Uniqueness      bool     `pulumi:"uniqueness"`
}

func GetZPASCIMAttributeHeaderOutput(ctx *pulumi.Context, args GetZPASCIMAttributeHeaderOutputArgs, opts ...pulumi.InvokeOption) GetZPASCIMAttributeHeaderResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetZPASCIMAttributeHeaderResult, error) {
			args := v.(GetZPASCIMAttributeHeaderArgs)
			r, err := GetZPASCIMAttributeHeader(ctx, &args, opts...)
			var s GetZPASCIMAttributeHeaderResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetZPASCIMAttributeHeaderResultOutput)
}

// A collection of arguments for invoking getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderOutputArgs struct {
	IdpName pulumi.StringPtrInput `pulumi:"idpName"`
	Name    pulumi.StringPtrInput `pulumi:"name"`
}

func (GetZPASCIMAttributeHeaderOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPASCIMAttributeHeaderArgs)(nil)).Elem()
}

// A collection of values returned by getZPASCIMAttributeHeader.
type GetZPASCIMAttributeHeaderResultOutput struct{ *pulumi.OutputState }

func (GetZPASCIMAttributeHeaderResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZPASCIMAttributeHeaderResult)(nil)).Elem()
}

func (o GetZPASCIMAttributeHeaderResultOutput) ToGetZPASCIMAttributeHeaderResultOutput() GetZPASCIMAttributeHeaderResultOutput {
	return o
}

func (o GetZPASCIMAttributeHeaderResultOutput) ToGetZPASCIMAttributeHeaderResultOutputWithContext(ctx context.Context) GetZPASCIMAttributeHeaderResultOutput {
	return o
}

func (o GetZPASCIMAttributeHeaderResultOutput) CanonicalValues() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) []string { return v.CanonicalValues }).(pulumi.StringArrayOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) CaseSensitive() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.CaseSensitive }).(pulumi.BoolOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.CreationTime }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) DataType() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.DataType }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) IdpId() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.IdpId }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) IdpName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) *string { return v.IdpName }).(pulumi.StringPtrOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) ModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.ModifiedTime }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Modifiedby() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Modifiedby }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Multivalued() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.Multivalued }).(pulumi.BoolOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Mutability() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Mutability }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Required() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.Required }).(pulumi.BoolOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Returned() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.Returned }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) SchemaUri() pulumi.StringOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) string { return v.SchemaUri }).(pulumi.StringOutput)
}

func (o GetZPASCIMAttributeHeaderResultOutput) Uniqueness() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZPASCIMAttributeHeaderResult) bool { return v.Uniqueness }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetZPASCIMAttributeHeaderResultOutput{})
}
