# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_zpa_app_connector_controller import *
from .get_zpa_app_connector_group import *
from .get_zpa_app_segment_browser_access import *
from .get_zpa_application_segment import *
from .get_zpa_application_server import *
from .get_zpa_ba_certificate import *
from .get_zpa_cloud_connector_group import *
from .get_zpa_customer_version_profile import *
from .get_zpa_enrollment_cert import *
from .get_zpa_id_p_controller import *
from .get_zpa_log_streaming_service import *
from .get_zpa_policy_type import *
from .get_zpa_posture_profile import *
from .get_zpa_provisioning_key import *
from .get_zpa_segment_group import *
from .get_zpa_server_group import *
from .get_zpa_service_edge_controller import *
from .get_zpa_service_edge_group import *
from .get_zpa_trusted_network import *
from .get_zpalss_config_client_types import *
from .get_zpalss_config_log_type_formats import *
from .get_zpalss_config_machine_group import *
from .get_zpalss_config_status_codes import *
from .get_zpasaml_attribute import *
from .get_zpascim_attribute_header import *
from .get_zpascim_groups import *
from .provider import *
from .zpa_app_connector_group import *
from .zpa_app_segment_browser_access import *
from .zpa_application_segment import *
from .zpa_application_server import *
from .zpa_log_streaming_service import *
from .zpa_policy_access_forwarding_rule import *
from .zpa_policy_access_rule import *
from .zpa_policy_access_timeout_rule import *
from .zpa_provisioning_key import *
from .zpa_segment_group import *
from .zpa_server_group import *
from .zpa_service_edge_group import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import willguibr_zpa.config as __config
    config = __config
else:
    config = _utilities.lazy_import('willguibr_zpa.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "zpa",
  "mod": "index/zPAAppConnectorGroup",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAAppConnectorGroup:ZPAAppConnectorGroup": "ZPAAppConnectorGroup"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAAppSegmentBrowserAccess",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAAppSegmentBrowserAccess:ZPAAppSegmentBrowserAccess": "ZPAAppSegmentBrowserAccess"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAApplicationSegment",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAApplicationSegment:ZPAApplicationSegment": "ZPAApplicationSegment"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAApplicationServer",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAApplicationServer:ZPAApplicationServer": "ZPAApplicationServer"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPALogStreamingService",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPALogStreamingService:ZPALogStreamingService": "ZPALogStreamingService"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAPolicyAccessForwardingRule",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAPolicyAccessForwardingRule:ZPAPolicyAccessForwardingRule": "ZPAPolicyAccessForwardingRule"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAPolicyAccessRule",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAPolicyAccessRule:ZPAPolicyAccessRule": "ZPAPolicyAccessRule"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAPolicyAccessTimeoutRule",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAPolicyAccessTimeoutRule:ZPAPolicyAccessTimeoutRule": "ZPAPolicyAccessTimeoutRule"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAProvisioningKey",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAProvisioningKey:ZPAProvisioningKey": "ZPAProvisioningKey"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPASegmentGroup",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPASegmentGroup:ZPASegmentGroup": "ZPASegmentGroup"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAServerGroup",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAServerGroup:ZPAServerGroup": "ZPAServerGroup"
  }
 },
 {
  "pkg": "zpa",
  "mod": "index/zPAServiceEdgeGroup",
  "fqn": "willguibr_zpa",
  "classes": {
   "zpa:index/zPAServiceEdgeGroup:ZPAServiceEdgeGroup": "ZPAServiceEdgeGroup"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "zpa",
  "token": "pulumi:providers:zpa",
  "fqn": "willguibr_zpa",
  "class": "Provider"
 }
]
"""
)
