# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetZPALSSConfigStatusCodesResult',
    'AwaitableGetZPALSSConfigStatusCodesResult',
    'get_zpalss_config_status_codes',
]

@pulumi.output_type
class GetZPALSSConfigStatusCodesResult:
    """
    A collection of values returned by getZPALSSConfigStatusCodes.
    """
    def __init__(__self__, id=None, zpn_ast_auth_log=None, zpn_auth_log=None, zpn_sys_auth_log=None, zpn_trans_log=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if zpn_ast_auth_log and not isinstance(zpn_ast_auth_log, dict):
            raise TypeError("Expected argument 'zpn_ast_auth_log' to be a dict")
        pulumi.set(__self__, "zpn_ast_auth_log", zpn_ast_auth_log)
        if zpn_auth_log and not isinstance(zpn_auth_log, dict):
            raise TypeError("Expected argument 'zpn_auth_log' to be a dict")
        pulumi.set(__self__, "zpn_auth_log", zpn_auth_log)
        if zpn_sys_auth_log and not isinstance(zpn_sys_auth_log, dict):
            raise TypeError("Expected argument 'zpn_sys_auth_log' to be a dict")
        pulumi.set(__self__, "zpn_sys_auth_log", zpn_sys_auth_log)
        if zpn_trans_log and not isinstance(zpn_trans_log, dict):
            raise TypeError("Expected argument 'zpn_trans_log' to be a dict")
        pulumi.set(__self__, "zpn_trans_log", zpn_trans_log)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="zpnAstAuthLog")
    def zpn_ast_auth_log(self) -> Mapping[str, str]:
        return pulumi.get(self, "zpn_ast_auth_log")

    @property
    @pulumi.getter(name="zpnAuthLog")
    def zpn_auth_log(self) -> Mapping[str, str]:
        return pulumi.get(self, "zpn_auth_log")

    @property
    @pulumi.getter(name="zpnSysAuthLog")
    def zpn_sys_auth_log(self) -> Mapping[str, str]:
        return pulumi.get(self, "zpn_sys_auth_log")

    @property
    @pulumi.getter(name="zpnTransLog")
    def zpn_trans_log(self) -> Mapping[str, str]:
        return pulumi.get(self, "zpn_trans_log")


class AwaitableGetZPALSSConfigStatusCodesResult(GetZPALSSConfigStatusCodesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetZPALSSConfigStatusCodesResult(
            id=self.id,
            zpn_ast_auth_log=self.zpn_ast_auth_log,
            zpn_auth_log=self.zpn_auth_log,
            zpn_sys_auth_log=self.zpn_sys_auth_log,
            zpn_trans_log=self.zpn_trans_log)


def get_zpalss_config_status_codes(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetZPALSSConfigStatusCodesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('zpa:index/getZPALSSConfigStatusCodes:getZPALSSConfigStatusCodes', __args__, opts=opts, typ=GetZPALSSConfigStatusCodesResult).value

    return AwaitableGetZPALSSConfigStatusCodesResult(
        id=__ret__.id,
        zpn_ast_auth_log=__ret__.zpn_ast_auth_log,
        zpn_auth_log=__ret__.zpn_auth_log,
        zpn_sys_auth_log=__ret__.zpn_sys_auth_log,
        zpn_trans_log=__ret__.zpn_trans_log)
