# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetZPALogStreamingServiceResult',
    'AwaitableGetZPALogStreamingServiceResult',
    'get_zpa_log_streaming_service',
    'get_zpa_log_streaming_service_output',
]

@pulumi.output_type
class GetZPALogStreamingServiceResult:
    """
    A collection of values returned by getZPALogStreamingService.
    """
    def __init__(__self__, configs=None, connector_groups=None, id=None, policy_rules=None):
        if configs and not isinstance(configs, list):
            raise TypeError("Expected argument 'configs' to be a list")
        pulumi.set(__self__, "configs", configs)
        if connector_groups and not isinstance(connector_groups, list):
            raise TypeError("Expected argument 'connector_groups' to be a list")
        pulumi.set(__self__, "connector_groups", connector_groups)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if policy_rules and not isinstance(policy_rules, list):
            raise TypeError("Expected argument 'policy_rules' to be a list")
        pulumi.set(__self__, "policy_rules", policy_rules)

    @property
    @pulumi.getter
    def configs(self) -> Sequence['outputs.GetZPALogStreamingServiceConfigResult']:
        return pulumi.get(self, "configs")

    @property
    @pulumi.getter(name="connectorGroups")
    def connector_groups(self) -> Sequence['outputs.GetZPALogStreamingServiceConnectorGroupResult']:
        return pulumi.get(self, "connector_groups")

    @property
    @pulumi.getter
    def id(self) -> Optional[str]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="policyRules")
    def policy_rules(self) -> Sequence['outputs.GetZPALogStreamingServicePolicyRuleResult']:
        return pulumi.get(self, "policy_rules")


class AwaitableGetZPALogStreamingServiceResult(GetZPALogStreamingServiceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetZPALogStreamingServiceResult(
            configs=self.configs,
            connector_groups=self.connector_groups,
            id=self.id,
            policy_rules=self.policy_rules)


def get_zpa_log_streaming_service(configs: Optional[Sequence[pulumi.InputType['GetZPALogStreamingServiceConfigArgs']]] = None,
                                  id: Optional[str] = None,
                                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetZPALogStreamingServiceResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['configs'] = configs
    __args__['id'] = id
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('zpa:index/getZPALogStreamingService:getZPALogStreamingService', __args__, opts=opts, typ=GetZPALogStreamingServiceResult).value

    return AwaitableGetZPALogStreamingServiceResult(
        configs=__ret__.configs,
        connector_groups=__ret__.connector_groups,
        id=__ret__.id,
        policy_rules=__ret__.policy_rules)


@_utilities.lift_output_func(get_zpa_log_streaming_service)
def get_zpa_log_streaming_service_output(configs: Optional[pulumi.Input[Optional[Sequence[pulumi.InputType['GetZPALogStreamingServiceConfigArgs']]]]] = None,
                                         id: Optional[pulumi.Input[Optional[str]]] = None,
                                         opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetZPALogStreamingServiceResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
