// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr.Outputs
{

    [OutputType]
    public sealed class GetZPACustomerVersionProfileVersionResult
    {
        public readonly string CreationTime;
        public readonly string CustomerId;
        public readonly string Id;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string Platform;
        public readonly string RestartAfterUptimeInDays;
        public readonly string Role;
        public readonly string Version;
        public readonly string VersionProfileGid;

        [OutputConstructor]
        private GetZPACustomerVersionProfileVersionResult(
            string creationTime,

            string customerId,

            string id,

            string modifiedTime,

            string modifiedby,

            string platform,

            string restartAfterUptimeInDays,

            string role,

            string version,

            string versionProfileGid)
        {
            CreationTime = creationTime;
            CustomerId = customerId;
            Id = id;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Platform = platform;
            RestartAfterUptimeInDays = restartAfterUptimeInDays;
            Role = role;
            Version = version;
            VersionProfileGid = versionProfileGid;
        }
    }
}
