// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr.Outputs
{

    [OutputType]
    public sealed class GetZPAIdPControllerAdminMetadataResult
    {
        public readonly string CertificateUrl;
        public readonly string SpBaseUrl;
        public readonly string SpEntityId;
        public readonly string SpMetadataUrl;
        public readonly string SpPostUrl;

        [OutputConstructor]
        private GetZPAIdPControllerAdminMetadataResult(
            string certificateUrl,

            string spBaseUrl,

            string spEntityId,

            string spMetadataUrl,

            string spPostUrl)
        {
            CertificateUrl = certificateUrl;
            SpBaseUrl = spBaseUrl;
            SpEntityId = spEntityId;
            SpMetadataUrl = spMetadataUrl;
            SpPostUrl = spPostUrl;
        }
    }
}
