// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr.Outputs
{

    [OutputType]
    public sealed class GetZPALogStreamingServicePolicyRuleConditionOperandResult
    {
        public readonly string CreationTime;
        public readonly string Id;
        public readonly string IdpId;
        public readonly string Lhs;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string Name;
        public readonly string ObjectType;
        public readonly string Operator;
        public readonly string Rhs;

        [OutputConstructor]
        private GetZPALogStreamingServicePolicyRuleConditionOperandResult(
            string creationTime,

            string id,

            string idpId,

            string lhs,

            string modifiedTime,

            string modifiedby,

            string name,

            string objectType,

            string @operator,

            string rhs)
        {
            CreationTime = creationTime;
            Id = id;
            IdpId = idpId;
            Lhs = lhs;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            ObjectType = objectType;
            Operator = @operator;
            Rhs = rhs;
        }
    }
}
