// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr.Outputs
{

    [OutputType]
    public sealed class GetZPALSSConfigMachineGroupMachineResult
    {
        public readonly string CreationTime;
        public readonly string Description;
        public readonly string Fingerprint;
        public readonly string Id;
        public readonly string IssuedCertId;
        public readonly string MachineGroupId;
        public readonly string MachineGroupName;
        public readonly string MachineTokenId;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> SigningCert;

        [OutputConstructor]
        private GetZPALSSConfigMachineGroupMachineResult(
            string creationTime,

            string description,

            string fingerprint,

            string id,

            string issuedCertId,

            string machineGroupId,

            string machineGroupName,

            string machineTokenId,

            string modifiedTime,

            string modifiedby,

            string name,

            ImmutableDictionary<string, string> signingCert)
        {
            CreationTime = creationTime;
            Description = description;
            Fingerprint = fingerprint;
            Id = id;
            IssuedCertId = issuedCertId;
            MachineGroupId = machineGroupId;
            MachineGroupName = machineGroupName;
            MachineTokenId = machineTokenId;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            SigningCert = signingCert;
        }
    }
}
