// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr.Outputs
{

    [OutputType]
    public sealed class ZPALogStreamingServicePolicyRuleResource
    {
        public readonly string? Action;
        public readonly string? ActionId;
        public readonly bool? BypassDefaultRule;
        public readonly ImmutableArray<Outputs.ZPALogStreamingServicePolicyRuleResourceCondition> Conditions;
        public readonly string? CustomMsg;
        public readonly bool? DefaultRule;
        public readonly string? Description;
        public readonly string? Id;
        public readonly bool? LssDefaultRule;
        public readonly string Name;
        public readonly string? Operator;
        public readonly string? PolicySetId;
        public readonly string? PolicyType;
        public readonly string? Priority;
        public readonly bool? ReauthDefaultRule;
        public readonly string? ReauthIdleTimeout;
        public readonly string? ReauthTimeout;
        public readonly string? RuleOrder;

        [OutputConstructor]
        private ZPALogStreamingServicePolicyRuleResource(
            string? action,

            string? actionId,

            bool? bypassDefaultRule,

            ImmutableArray<Outputs.ZPALogStreamingServicePolicyRuleResourceCondition> conditions,

            string? customMsg,

            bool? defaultRule,

            string? description,

            string? id,

            bool? lssDefaultRule,

            string name,

            string? @operator,

            string? policySetId,

            string? policyType,

            string? priority,

            bool? reauthDefaultRule,

            string? reauthIdleTimeout,

            string? reauthTimeout,

            string? ruleOrder)
        {
            Action = action;
            ActionId = actionId;
            BypassDefaultRule = bypassDefaultRule;
            Conditions = conditions;
            CustomMsg = customMsg;
            DefaultRule = defaultRule;
            Description = description;
            Id = id;
            LssDefaultRule = lssDefaultRule;
            Name = name;
            Operator = @operator;
            PolicySetId = policySetId;
            PolicyType = policyType;
            Priority = priority;
            ReauthDefaultRule = reauthDefaultRule;
            ReauthIdleTimeout = reauthIdleTimeout;
            ReauthTimeout = reauthTimeout;
            RuleOrder = ruleOrder;
        }
    }
}
