// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr.Inputs
{

    public sealed class ZPAAppSegmentBrowserAccessClientlessAppGetArgs : Pulumi.ResourceArgs
    {
        [Input("allowOptions")]
        public Input<bool>? AllowOptions { get; set; }

        [Input("appId")]
        public Input<string>? AppId { get; set; }

        [Input("applicationPort")]
        public Input<string>? ApplicationPort { get; set; }

        [Input("applicationProtocol", required: true)]
        public Input<string> ApplicationProtocol { get; set; } = null!;

        [Input("certificateId", required: true)]
        public Input<string> CertificateId { get; set; } = null!;

        [Input("certificateName")]
        public Input<string>? CertificateName { get; set; }

        [Input("cname")]
        public Input<string>? Cname { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("hidden")]
        public Input<bool>? Hidden { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("localDomain")]
        public Input<string>? LocalDomain { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("trustUntrustedCert")]
        public Input<bool>? TrustUntrustedCert { get; set; }

        public ZPAAppSegmentBrowserAccessClientlessAppGetArgs()
        {
        }
    }
}
