// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.willguibr.Inputs
{

    public sealed class ZPALogStreamingServicePolicyRuleResourceConditionArgs : Pulumi.ResourceArgs
    {
        [Input("negated")]
        public Input<bool>? Negated { get; set; }

        [Input("operands")]
        private InputList<Inputs.ZPALogStreamingServicePolicyRuleResourceConditionOperandArgs>? _operands;
        public InputList<Inputs.ZPALogStreamingServicePolicyRuleResourceConditionOperandArgs> Operands
        {
            get => _operands ?? (_operands = new InputList<Inputs.ZPALogStreamingServicePolicyRuleResourceConditionOperandArgs>());
            set => _operands = value;
        }

        [Input("operator", required: true)]
        public Input<string> Operator { get; set; } = null!;

        public ZPALogStreamingServicePolicyRuleResourceConditionArgs()
        {
        }
    }
}
