// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getZPAEnrollmentCert(args?: GetZPAEnrollmentCertArgs, opts?: pulumi.InvokeOptions): Promise<GetZPAEnrollmentCertResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("zpa:index/getZPAEnrollmentCert:getZPAEnrollmentCert", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPAEnrollmentCert.
 */
export interface GetZPAEnrollmentCertArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getZPAEnrollmentCert.
 */
export interface GetZPAEnrollmentCertResult {
    readonly allowSigning: boolean;
    readonly certificate: string;
    readonly clientCertType: string;
    readonly cname: string;
    readonly creationTime: string;
    readonly csr: string;
    readonly description: string;
    readonly id?: string;
    readonly issuedBy: string;
    readonly issuedTo: string;
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly name?: string;
    readonly parentCertId: string;
    readonly parentCertName: string;
    readonly privateKey: string;
    readonly privateKeyPresent: boolean;
    readonly serialNo: string;
    readonly validFromInEpochSec: string;
    readonly validToInEpochSec: string;
    readonly zrsaEncryptedPrivateKey: string;
    readonly zrsaEncryptedSessionKey: string;
}

export function getZPAEnrollmentCertOutput(args?: GetZPAEnrollmentCertOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPAEnrollmentCertResult> {
    return pulumi.output(args).apply(a => getZPAEnrollmentCert(a, opts))
}

/**
 * A collection of arguments for invoking getZPAEnrollmentCert.
 */
export interface GetZPAEnrollmentCertOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
