// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getZPASAMLAttribute(args?: GetZPASAMLAttributeArgs, opts?: pulumi.InvokeOptions): Promise<GetZPASAMLAttributeResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("zpa:index/getZPASAMLAttribute:getZPASAMLAttribute", {
        "id": args.id,
        "idpName": args.idpName,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPASAMLAttribute.
 */
export interface GetZPASAMLAttributeArgs {
    id?: string;
    idpName?: string;
    name?: string;
}

/**
 * A collection of values returned by getZPASAMLAttribute.
 */
export interface GetZPASAMLAttributeResult {
    readonly creationTime: string;
    readonly id: string;
    readonly idpId: string;
    readonly idpName?: string;
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly name: string;
    readonly samlName: string;
    readonly userAttribute: boolean;
}

export function getZPASAMLAttributeOutput(args?: GetZPASAMLAttributeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPASAMLAttributeResult> {
    return pulumi.output(args).apply(a => getZPASAMLAttribute(a, opts))
}

/**
 * A collection of arguments for invoking getZPASAMLAttribute.
 */
export interface GetZPASAMLAttributeOutputArgs {
    id?: pulumi.Input<string>;
    idpName?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
