// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getZPALSSConfigMachineGroup(args?: GetZPALSSConfigMachineGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetZPALSSConfigMachineGroupResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("zpa:index/getZPALSSConfigMachineGroup:getZPALSSConfigMachineGroup", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPALSSConfigMachineGroup.
 */
export interface GetZPALSSConfigMachineGroupArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getZPALSSConfigMachineGroup.
 */
export interface GetZPALSSConfigMachineGroupResult {
    readonly creationTime: string;
    readonly description: string;
    readonly enabled: boolean;
    readonly id?: string;
    readonly machines: outputs.GetZPALSSConfigMachineGroupMachine[];
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly name?: string;
}

export function getZPALSSConfigMachineGroupOutput(args?: GetZPALSSConfigMachineGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPALSSConfigMachineGroupResult> {
    return pulumi.output(args).apply(a => getZPALSSConfigMachineGroup(a, opts))
}

/**
 * A collection of arguments for invoking getZPALSSConfigMachineGroup.
 */
export interface GetZPALSSConfigMachineGroupOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
