// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getZPAApplicationSegment(args?: GetZPAApplicationSegmentArgs, opts?: pulumi.InvokeOptions): Promise<GetZPAApplicationSegmentResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("zpa:index/getZPAApplicationSegment:getZPAApplicationSegment", {
        "id": args.id,
        "name": args.name,
        "tcpPortRanges": args.tcpPortRanges,
        "udpPortRanges": args.udpPortRanges,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPAApplicationSegment.
 */
export interface GetZPAApplicationSegmentArgs {
    id?: string;
    name?: string;
    tcpPortRanges?: inputs.GetZPAApplicationSegmentTcpPortRange[];
    udpPortRanges?: inputs.GetZPAApplicationSegmentUdpPortRange[];
}

/**
 * A collection of values returned by getZPAApplicationSegment.
 */
export interface GetZPAApplicationSegmentResult {
    readonly bypassType: string;
    readonly configSpace: string;
    readonly creationTime: string;
    readonly defaultIdleTimeout: string;
    readonly defaultMaxAge: string;
    readonly description: string;
    readonly domainNames: string[];
    readonly doubleEncrypt: boolean;
    readonly enabled: boolean;
    readonly healthChecktype: string;
    readonly healthReporting: string;
    readonly id?: string;
    readonly ipAnchored: boolean;
    readonly isCnameEnabled: boolean;
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly name?: string;
    readonly passiveHealthEnabled: boolean;
    readonly segmentGroupId: string;
    readonly segmentGroupName: string;
    readonly serverGroups: outputs.GetZPAApplicationSegmentServerGroup[];
    readonly tcpPortRanges: string[];
    readonly udpPortRanges: string[];
}

export function getZPAApplicationSegmentOutput(args?: GetZPAApplicationSegmentOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPAApplicationSegmentResult> {
    return pulumi.output(args).apply(a => getZPAApplicationSegment(a, opts))
}

/**
 * A collection of arguments for invoking getZPAApplicationSegment.
 */
export interface GetZPAApplicationSegmentOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    tcpPortRanges?: pulumi.Input<pulumi.Input<inputs.GetZPAApplicationSegmentTcpPortRangeArgs>[]>;
    udpPortRanges?: pulumi.Input<pulumi.Input<inputs.GetZPAApplicationSegmentUdpPortRangeArgs>[]>;
}
