// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getZPAPostureProfile(args?: GetZPAPostureProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetZPAPostureProfileResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("zpa:index/getZPAPostureProfile:getZPAPostureProfile", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPAPostureProfile.
 */
export interface GetZPAPostureProfileArgs {
    name?: string;
}

/**
 * A collection of values returned by getZPAPostureProfile.
 */
export interface GetZPAPostureProfileResult {
    readonly creationTime: string;
    readonly domain: string;
    readonly id: string;
    readonly masterCustomerId: string;
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly name?: string;
    readonly postureUdid: string;
    readonly zscalerCloud: string;
    readonly zscalerCustomerId: string;
}

export function getZPAPostureProfileOutput(args?: GetZPAPostureProfileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPAPostureProfileResult> {
    return pulumi.output(args).apply(a => getZPAPostureProfile(a, opts))
}

/**
 * A collection of arguments for invoking getZPAPostureProfile.
 */
export interface GetZPAPostureProfileOutputArgs {
    name?: pulumi.Input<string>;
}
