// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getZPASCIMAttributeHeader(args?: GetZPASCIMAttributeHeaderArgs, opts?: pulumi.InvokeOptions): Promise<GetZPASCIMAttributeHeaderResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("zpa:index/getZPASCIMAttributeHeader:getZPASCIMAttributeHeader", {
        "idpName": args.idpName,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZPASCIMAttributeHeader.
 */
export interface GetZPASCIMAttributeHeaderArgs {
    idpName?: string;
    name?: string;
}

/**
 * A collection of values returned by getZPASCIMAttributeHeader.
 */
export interface GetZPASCIMAttributeHeaderResult {
    readonly canonicalValues: string[];
    readonly caseSensitive: boolean;
    readonly creationTime: string;
    readonly dataType: string;
    readonly description: string;
    readonly id: string;
    readonly idpId: string;
    readonly idpName?: string;
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly multivalued: boolean;
    readonly mutability: string;
    readonly name?: string;
    readonly required: boolean;
    readonly returned: string;
    readonly schemaUri: string;
    readonly uniqueness: boolean;
}

export function getZPASCIMAttributeHeaderOutput(args?: GetZPASCIMAttributeHeaderOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZPASCIMAttributeHeaderResult> {
    return pulumi.output(args).apply(a => getZPASCIMAttributeHeader(a, opts))
}

/**
 * A collection of arguments for invoking getZPASCIMAttributeHeader.
 */
export interface GetZPASCIMAttributeHeaderOutputArgs {
    idpName?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
